apiVersion: v1
kind: Service
metadata:
  name: admin-service
  namespace: scd-project
spec:
  type: NodePort
  selector:
    app: admin
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30001
