apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
  namespace: scd-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
      - name: admin
        image: m33na04/admin:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          value: mongodb://mongo-service:27017/docdoc

