name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main  # Change to 'master' if that's your default branch

jobs:
  build-deploy:
    runs-on: self-hosted  # This tells GitHub to run this job on your local self-hosted runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker to use Minikube's environment
      run: |
        echo "Configuring Docker to use Minikube's daemon..."
        eval $(minikube docker-env)

    - name: Build Docker image
      run: |
        docker build -t your-dockerhub-username/your-app-name:latest .

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image to Docker Hub
      run: docker push your-dockerhub-username/your-app-name:latest

    - name: Deploy to Minikube
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
